services:

  rabbitmq:
    image: rabbitmq:3-management
    container_name: some-rabbit
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "check_running", "-q"]
      interval: 30s
      timeout: 30s
      retries: 3


  agent-worker:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        RMQ_AI_URL: "amqp://guest:guest@rabbitmq:5672/%2F"
    container_name: order-agent-worker

    restart: on-failure
    depends_on:
      rabbitmq:
        condition: service_healthy